version: "3.11.8"
services:
  rabbitmq_shovel:
    image: rabbitmq:3.9.16-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-conf:/etc/rabbitmq
      - ./shovel_create.sh:/shovel_create.sh
    networks:
      - rabbit-shovel-net

  rabbitmq_downstream:
    image: rabbitmq:3.9.16-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq-conf:/etc/rabbitmq
    networks:
      - rabbit-shovel-net     

networks:
  rabbit-shovel-net:
    name: rabbit-shovel-net
    driver: bridge